### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by Fotguedes** [cgsvv/AISubtitle#1]
Hey,
I found this repo and was really exciting with the possibilities. I tried deploying it, using the api from chatgpt, but i keep receiving the following error

`translate failedSyntaxError: Unexpected token 'A', "A server e"... is not valid JSON`

Do you know what it could be that i'm doing wrong? I'm not able to even translate the text that is already there as an example

**Comment by cgsvv** [comment]
Sorry, I think I forget to add these redis env as required. You should also add them in your environment. (you can apply a upstash redis url and token)

UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=
UPSTASH_RATE_REDIS_REST_URL=
UPSTASH_RATE_REDIS_REST_TOKEN=

OR maybe you could just disable them in the middleware and translate file

**Comment by Fotguedes** [comment]
Hmm, i'll search about the upstash, since i've never used it.
Am I able to translate it without them? I opened the "middleware.ts" and was not able to find what I should disable

**Comment by cgsvv** [comment]
There are two places using redis:
1. caching translate results. You can try to search " Redis.fromEnv " and disable it
2. rate limit. You can search "ratelimit" and disable it.
They both can be disabled.

**Comment by Fotguedes** [comment]
Yeah, I failed disabling it, i'll learn how to use redis... Your repo is the only one that is currently translating ass subtitles, so i'm looking foward to be able to use it haha
