### ISSUE TITLE
环境变量配置问题

### ISSUE THREAD

**Issue by Mylszd** [cgsvv/AISubtitle#10]
请问
BILIBILI_SESSION_TOKEN=
SAVESUBS_X_AUTH_TOKEN=
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=
UPSTASH_RATE_REDIS_REST_URL=
UPSTASH_RATE_REDIS_REST_TOKEN=
NEXT_PUBLIC_SENTRY_DSN=
这些变量都要怎么配置，小白一枚，谢谢。。。。

**Comment by cgsvv** [comment]
REDIS相关的需要去upstatsh申请一个免费的redis链接即可。其他的如果用不上不用配置
