### ISSUE TITLE
能否添加一个自定义OpenAI API Host的设置选项呢

### ISSUE THREAD

**Issue by Wutpeach** [cgsvv/AISubtitle#11]
官网的api续费太过困难了，因此在国内的代理平台获取了3.5的api，但没法直接应用到aisubtitle中。希望能增加一个api host的设置选项，哭哭🥲

**Comment by lhj5426** [comment]
还有20天免费api 到期了确实需要一个 一个可以自定义第三方API的接口

**Comment by jkhcc11** [comment]
可以看看这个forked  [https://github.com/jkhcc11/AISubtitle](url) 已实现
