### ISSUE TITLE
本地部署报错

### ISSUE THREAD

**Issue by eatingmiao** [cgsvv/AISubtitle#13]
为什么本地部署后api请求错误呢
http://localhost:3000/api/translate
Status Code: 500 Internal Server Error
response是html本身<!DOCTYPE html><html lang="en">...</html>

**Comment by cgsvv** [comment]
看下你的启动日志有没有报错哈～还有检查一下你是否是用的npm run dev启动的哈

**Comment by eatingmiao** [comment]
> 看下你的启动日志有没有报错哈～还有检查一下你是否是用的npm run dev启动的哈

我用过npm run dev启动的，node版本是16.19.0；
启动后没有报错，点击翻译本页按钮会报错：
wait  - compiling /_error (client and server)...
error - node_modules/@upstash/redis/esm/platforms/nodejs.js (22:0) @ <unknown>
error - Cannot read properties of undefined (reading 'startsWith')

**Comment by cgsvv** [comment]
看样子还是upstash redis的问题，估计需要设置环境变量里的redis 那几个

**Comment by eatingmiao** [comment]
> 
我以为UPSTASH的变量是非必填的呢
我后来把openai的地址换成代理地址https://api.openai-proxy.com/就成功了
谢谢提示
