### ISSUE TITLE
翻译失败SyntaxError: Unexpected token 'A', "A server e"... is not valid JSON

### ISSUE THREAD

**Issue by mm519897405** [cgsvv/AISubtitle#2]
使用Deploy部署后，提示
翻译失败SyntaxError: Unexpected token 'A', "A server e"... is not valid JSON

**Comment by cgsvv** [comment]
参见第一个问题哈，你还需要提供Redis的环境变量   #1

**Comment by mm519897405** [comment]
> 参见第一个问题哈，你还需要提供Redis的环境变量 #1

感谢提供解决方式，不过我是个小白，还是期待一个更简单配置的版本了😄

**Comment by mm519897405** [comment]
> 参见第一个问题哈，你还需要提供Redis的环境变量 #1

感谢提供解决方式，不过我是个小白，还是期待一个更简单配置的版本了😄
