### ISSUE TITLE
How do I set up a proxy? Even when I enable global proxy settings, I can't connect.

### ISSUE THREAD

**Issue by Hipponensis** [cgsvv/AISubtitle#3]
API error  [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
} fetch failed

**Comment by Hipponensis** [comment]
also use Google Translate

**Comment by cgsvv** [comment]
Please note that we use nextjs api to fetch content, and it is running in the nodejs process, not your browser. So make sure your nodejs env (eg. the terminal) has access to proxy.
