### ISSUE TITLE
add Persian language 

### ISSUE THREAD

**Issue by fontgah** [cgsvv/AISubtitle#5]
Hello, please add Persian language support and support for Unicode and RTL.

**Comment by cgsvv** [comment]
Hi, I added a checkout to enable select all the available language, please check the new version. As for  Unicode and RTL support, I currently don't what the problem is 😂 Maybe you can provide more info.

**Comment by fontgah** [comment]
I checked and Persian language was not added. It’s not on the list of languages.
https://i.postimg.cc/B6HrZhj0/Untitled.jpg
https://ai.cgsv.top/

**Comment by cgsvv** [comment]
Please try to toggle the checkbox right after the language selection dropdown..
