### ISSUE TITLE
选择翻译时报错'API Too Many Requests'

### ISSUE THREAD

**Issue by haoxiongliu** [cgsvv/AISubtitle#8]

**Comment by haoxiongliu** [comment]
![image](https://user-images.githubusercontent.com/26861527/228306653-a1092c9b-ca40-47c1-96cd-39f69887e132.png)

**Comment by haoxiongliu** [comment]
![image](https://user-images.githubusercontent.com/26861527/228306961-00586065-68ca-4d9c-acbb-1bea9d6524b6.png)
翻译网页默认的文本没有问题

**Comment by cgsvv** [comment]
用的是个类似模拟网页请求的翻译API，会被限速，不是很稳定哈
